const authors=["A Yoe",
"Akyi Taw",
"Akyi Taw",
"Akyin Nar Mon",
"Ashin Eiddhi Pala",
"Ashin Sandar Hti Ka",
"Aung Aye (Yangon University)",
"Aung Cheint",
"Aung Cheint",
"Aung Thin",
"Aung Tun",
"British Ko Ko Maung",
"British Ko Ko Maung",
"British Ko Ko Maung",
"British Ko Ko Maung",
"Cambridge",
"Cambridge",
"Chan Myae Win",
"Chan Myae Win",
"Chan Myae Win",
"Chan Myae Win",
"Chan Myae Win",
"Chit Oo Nyo",
"Chit Oo Nyo",
"Chit Oo Nyo",
"Chit Oo Nyo",
"Cho Paing Naung",
"Cho Paing Naung",
"Collin",
"Collin",
"D No Vo",
"Dr. Aung Myint Oo",
"Dr.Phyo Thiha",
"Dr.Phyo Thiha",
"Dr.Phyo Thiha",
"Dr.Phyo Thiha",
"Hla Than",
"Htet Htet Htun",
"Htet Htet Htun",
"Htet Yei",
"Jauk Jack",
"Jessica Mozart",
"Journal Kyaw Ma Ma Lay",
"Journal Kyaw Ma Ma Lay",
"Journal Kyaw Ma Ma Lay",
"Journal Kyaw Ma Ma Lay",
"Journal Kyaw Ma Ma Lay",
"Journal Kyaw Ma Ma Lay",
"Journal Kyaw Ma Ma Lay",
"Journal Kyaw Ma Ma Lay",
"Journal Kyaw U Chit Mg",
"Juu",
"Juu",
"Juu",
"Juu",
"Juu",
"Juu",
"Juu",
"Juu",
"Juu",
"Juu",
"Juu",
"Kaung Thar",
"Khet Zaw",
"Khet Zaw",
"Khet Zaw",
"Khet Zaw",
"Khet Zaw",
"Khin Hnin Yu",
"Khin Hnin Yu",
"Khin Hnin Yu",
"Khin Hnin Yu",
"Khin Hnin Yu",
"Khin Hnin Yu",
"Khin Khin Htoo",
"Khin Khin Htoo",
"Khin Khin Htoo",
"Khin Khin Htoo",
"Khin Khin Htoo",
"Khin Khin Htoo",
"Khin Khin Htoo",
"Khin Khin Htoo",
"Khin Khin Htoo",
"Ko Ko Lay",
"Kyal Sin Yu Mon",
"Kyar Pauk",
"Kyaw Yin Myint ",
"Kyi Aye",
"Kyi Aye",
"Kyi Aye",
"Lal Twin Thar Saw Chit",
"Lu Du Daw AMar",
"Lu Thar Man",
"Lynn Khant",
"Lynn Tint Thiha",
"Lynn Yaung Sin",
"Lynn Yaung Sin",
"Ma Sandar",
"Ma Thida (Sanchaung)",
"Ma Thida (Sanchaung)",
"Ma Thida (Sanchaung)",
"Ma Thida (Sanchaung)",
"Mar Yin Yin",
"Mar Yin Yin",
"Mar Yin Yin",
"Maung Moe Thu",
"Maung Myint Kywe",
"Maung Paw Tun",
"Maung Thar Cho",
"Maung Thein Saing",
"Maung Thein Saing",
"Maung Tun Thu",
"Maung Tun Thu",
"Maung Tun Thu",
"Maung Tun Thu",
"Maung Tun Thu",
"Maung Tun Thu",
"Maung Tun Thu",
"Mi Man Lay",
"Min Aung Min",
"Min Din",
"Min Khite Soe San",
"Min Khite Soe San",
"Min Khite Soe San",
"Min Ko Naing",
"Min Ko Naing",
"Min Ko Naing",
"Min Lu",
"Min Lu",
"Min Lu",
"Min Lu",
"Min Lu",
"Min Lu",
"Min Lu",
"Min Lu",
"Min Lu",
"Min Lu",
"Min Lu",
"Min Lu",
"Min Lu",
"Min Lu",
"Moe Moe(Innyar)",
"Moe Moe(Innyar)",
"Moe Moe(Innyar)",
"Moe Shin",
"Moe Shin",
"Moe Shin",
"Mon Halsey",
"Mon Halsey",
"Mon Halsey",
"Mon Halsey",
"Mon Halsey",
"Mya Kyay",
"Mya Kyay",
"Mya Than Tint",
"Mya Than Tint",
"Mya Than Tint",
"Mya Than Tint",
"Mya Than Tint",
"Mya Than Tint",
"Mya Than Tint",
"Mya Than Tint",
"Myat Nyein ",
"Myay Hmone Lwin",
"Myay Hmone Lwin",
"Myit Kyoe Inn",
"Naing Win Swe",
"Nanda Sarya",
"Nanda Thein Zan",
"Nanda Thein Zan",
"Nat Nwe",
"Nat Nwe",
"Nat Nwe",
"Ngu War Kyaw Oo",
"Ni Ko Ye",
"Ni Ko Ye",
"Ni Ko Ye",
"Nine Nine Sa Nay",
"Nine Nine Sa Nay",
"No Shi",
"Nu Nu Yi Innwa ",
"Nu Nu Yi Innwa ",
"Nu Nu Yi Innwa ",
"Nu Nu Yi Innwa ",
"Nu Nu Yi Innwa ",
"Nu Nu Yi Innwa ",
"Nu Nu Yi Innwa ",
"Nu Nu Yi Innwa ",
"Nyan Wai",
"Nyi Pu Lay",
"Oxford Sayar Taw",
"Papillon",
"Papillon",
"Par Ya Gu",
"Par Ya Gu",
"Pe Moe Hnin",
"Pe Moe Hnin",
"Pe Moe Hnin",
"Pe Moe Hnin",
"Pe Moe Hnin",
"Phay Myint",
"Phone Naing ",
"Phone Naing ",
"Phone Naing ",
"Phone Naing ",
"Phone Naing ",
"Phone Naing ",
"Phraw San",
"Pone Nya Khin",
"Pone Nya Khin",
"Pone Nya Khin",
"Pone Nya Khin",
"Pone Nya Khin",
"Raymond Murphy",
"Raymond Murphy",
"Raymond Murphy(WE)",
"San Shwe Myint",
"Sapal Phyu Nu",
"Seint San Phyu",
"Shwe Ou Daung",
"Shwe Ou Daung",
"Shwe Ou Daung",
"Shwe Ou Daung",
"Shwe Ou Daung",
"Shwe Ou Daung",
"Shwe Ou Daung",
"Shwe Ou Daung",
"Shwe Ou Daung",
"Shwe Ou Daung",
"Shwe Ou Daung",
"Shwe Ou Daung",
"Sit Nyein",
"Sit Nyein",
"Soe Htike (Phado)",
"Soe Htike (Phado)",
"Soe Htike (Phado)",
"Su Chi Ko",
"Su Chi Ko",
"Than Myint Aung",
"Thandar",
"Thaw Dar Dwe",
"Thaw Dar Swe",
"Thaw Dar Swe",
"Thaw Dar Swe",
"Thaw Dar Swe",
"Thaw Dar Swe",
"Thein Phay Myint",
"Thein Phay Myint",
"Thein Phay Myint",
"Thein Phay Myint",
"Thein Phay Myint",
"Thu Maung",
"Tin Moe",
"Tin Nyunt",
"Tin Nyunt",
"Tin Nyunt",
"Tin Nyunt",
"Tin Nyunt",
"Tin Nyunt",
"Tristan Pyne",
"Tut Pe",
"Tut Pe",
"Tut Pe",
"Tut Pe",
"Tut Pe",
"Tut Pe",
"Tut Pe",
"Tut Pe",
"Tut Pe",
"Tut Pe",
"Tut Pe",
"U Aung Khin",
"U Chan Mya",
"U Nu",
"U Nu",
"U Nu",
"U Nu",
"U Phoe Kyar",
"U Thu Kha",
"Various Author",
"Win Nyein",
"Win Nyein",
"Win Nyein",
"Win Nyein",
"Win Nyein",
"Win Nyein",
"Win Tin",
"Win Win Latt",
"Yarzar Wizaya",
"Yin Maung",
"Yu Ya",
"Zaw Win Kyu",
"Zaw Win Kyu"];

const bookstoreAuthors = [...new Set(authors)];
console.log(bookstoreAuthors);